// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.21.2
// source: pkg/proto/device_health_check.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DeviceService_ServingStatus int32

const (
	DeviceService_UNKNOWN         DeviceService_ServingStatus = 0
	DeviceService_SERVING         DeviceService_ServingStatus = 1
	DeviceService_NOT_SERVING     DeviceService_ServingStatus = 2
	DeviceService_SERVICE_UNKNOWN DeviceService_ServingStatus = 3 // Used only by the Watch method.
)

// Enum value maps for DeviceService_ServingStatus.
var (
	DeviceService_ServingStatus_name = map[int32]string{
		0: "UNKNOWN",
		1: "SERVING",
		2: "NOT_SERVING",
		3: "SERVICE_UNKNOWN",
	}
	DeviceService_ServingStatus_value = map[string]int32{
		"UNKNOWN":         0,
		"SERVING":         1,
		"NOT_SERVING":     2,
		"SERVICE_UNKNOWN": 3,
	}
)

func (x DeviceService_ServingStatus) Enum() *DeviceService_ServingStatus {
	p := new(DeviceService_ServingStatus)
	*p = x
	return p
}

func (x DeviceService_ServingStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DeviceService_ServingStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_pkg_proto_device_health_check_proto_enumTypes[0].Descriptor()
}

func (DeviceService_ServingStatus) Type() protoreflect.EnumType {
	return &file_pkg_proto_device_health_check_proto_enumTypes[0]
}

func (x DeviceService_ServingStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DeviceService_ServingStatus.Descriptor instead.
func (DeviceService_ServingStatus) EnumDescriptor() ([]byte, []int) {
	return file_pkg_proto_device_health_check_proto_rawDescGZIP(), []int{2, 0}
}

type InitRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *InitRequest) Reset() {
	*x = InitRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_device_health_check_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitRequest) ProtoMessage() {}

func (x *InitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_device_health_check_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitRequest.ProtoReflect.Descriptor instead.
func (*InitRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_device_health_check_proto_rawDescGZIP(), []int{0}
}

type DeviceReportRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MachineID string `protobuf:"bytes,1,opt,name=machineID,proto3" json:"machineID,omitempty"`
}

func (x *DeviceReportRequest) Reset() {
	*x = DeviceReportRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_device_health_check_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeviceReportRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceReportRequest) ProtoMessage() {}

func (x *DeviceReportRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_device_health_check_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceReportRequest.ProtoReflect.Descriptor instead.
func (*DeviceReportRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_device_health_check_proto_rawDescGZIP(), []int{1}
}

func (x *DeviceReportRequest) GetMachineID() string {
	if x != nil {
		return x.MachineID
	}
	return ""
}

type DeviceService struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name   string                      `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Status DeviceService_ServingStatus `protobuf:"varint,2,opt,name=status,proto3,enum=DeviceService_ServingStatus" json:"status,omitempty"`
	Reason string                      `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
}

func (x *DeviceService) Reset() {
	*x = DeviceService{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_device_health_check_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeviceService) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceService) ProtoMessage() {}

func (x *DeviceService) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_device_health_check_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceService.ProtoReflect.Descriptor instead.
func (*DeviceService) Descriptor() ([]byte, []int) {
	return file_pkg_proto_device_health_check_proto_rawDescGZIP(), []int{2}
}

func (x *DeviceService) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DeviceService) GetStatus() DeviceService_ServingStatus {
	if x != nil {
		return x.Status
	}
	return DeviceService_UNKNOWN
}

func (x *DeviceService) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type DeviceReportResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DeviceReportResponse) Reset() {
	*x = DeviceReportResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_device_health_check_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeviceReportResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceReportResponse) ProtoMessage() {}

func (x *DeviceReportResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_device_health_check_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceReportResponse.ProtoReflect.Descriptor instead.
func (*DeviceReportResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_device_health_check_proto_rawDescGZIP(), []int{3}
}

var File_pkg_proto_device_health_check_proto protoreflect.FileDescriptor

var file_pkg_proto_device_health_check_proto_rawDesc = []byte{
	0x0a, 0x23, 0x70, 0x6b, 0x67, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x64, 0x65, 0x76, 0x69,
	0x63, 0x65, 0x5f, 0x68, 0x65, 0x61, 0x6c, 0x74, 0x68, 0x5f, 0x63, 0x68, 0x65, 0x63, 0x6b, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x0d, 0x0a, 0x0b, 0x49, 0x6e, 0x69, 0x74, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x22, 0x33, 0x0a, 0x13, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x52, 0x65,
	0x70, 0x6f, 0x72, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x6d,
	0x61, 0x63, 0x68, 0x69, 0x6e, 0x65, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09,
	0x6d, 0x61, 0x63, 0x68, 0x69, 0x6e, 0x65, 0x49, 0x44, 0x22, 0xc2, 0x01, 0x0a, 0x0d, 0x44, 0x65,
	0x76, 0x69, 0x63, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12,
	0x34, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32,
	0x1c, 0x2e, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e,
	0x53, 0x65, 0x72, 0x76, 0x69, 0x6e, 0x67, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x22, 0x4f, 0x0a,
	0x0d, 0x53, 0x65, 0x72, 0x76, 0x69, 0x6e, 0x67, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x0b,
	0x0a, 0x07, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x10, 0x00, 0x12, 0x0b, 0x0a, 0x07, 0x53,
	0x45, 0x52, 0x56, 0x49, 0x4e, 0x47, 0x10, 0x01, 0x12, 0x0f, 0x0a, 0x0b, 0x4e, 0x4f, 0x54, 0x5f,
	0x53, 0x45, 0x52, 0x56, 0x49, 0x4e, 0x47, 0x10, 0x02, 0x12, 0x13, 0x0a, 0x0f, 0x53, 0x45, 0x52,
	0x56, 0x49, 0x43, 0x45, 0x5f, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x10, 0x03, 0x22, 0x16,
	0x0a, 0x14, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x52, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x32, 0x46, 0x0a, 0x0c, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65,
	0x48, 0x65, 0x61, 0x6c, 0x74, 0x68, 0x12, 0x36, 0x0a, 0x05, 0x57, 0x61, 0x74, 0x63, 0x68, 0x12,
	0x14, 0x2e, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x52, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x15, 0x2e, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x52, 0x65,
	0x70, 0x6f, 0x72, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x28, 0x01, 0x42, 0x36,
	0x0a, 0x13, 0x63, 0x6e, 0x2e, 0x61, 0x63, 0x2e, 0x6e, 0x74, 0x73, 0x63, 0x2e, 0x74, 0x61, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x42, 0x16, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x48, 0x65, 0x61,
	0x6c, 0x74, 0x68, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x50, 0x01, 0x5a,
	0x05, 0x2e, 0x2f, 0x3b, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pkg_proto_device_health_check_proto_rawDescOnce sync.Once
	file_pkg_proto_device_health_check_proto_rawDescData = file_pkg_proto_device_health_check_proto_rawDesc
)

func file_pkg_proto_device_health_check_proto_rawDescGZIP() []byte {
	file_pkg_proto_device_health_check_proto_rawDescOnce.Do(func() {
		file_pkg_proto_device_health_check_proto_rawDescData = protoimpl.X.CompressGZIP(file_pkg_proto_device_health_check_proto_rawDescData)
	})
	return file_pkg_proto_device_health_check_proto_rawDescData
}

var file_pkg_proto_device_health_check_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_pkg_proto_device_health_check_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_pkg_proto_device_health_check_proto_goTypes = []interface{}{
	(DeviceService_ServingStatus)(0), // 0: DeviceService.ServingStatus
	(*InitRequest)(nil),              // 1: InitRequest
	(*DeviceReportRequest)(nil),      // 2: DeviceReportRequest
	(*DeviceService)(nil),            // 3: DeviceService
	(*DeviceReportResponse)(nil),     // 4: DeviceReportResponse
}
var file_pkg_proto_device_health_check_proto_depIdxs = []int32{
	0, // 0: DeviceService.status:type_name -> DeviceService.ServingStatus
	2, // 1: DeviceHealth.Watch:input_type -> DeviceReportRequest
	4, // 2: DeviceHealth.Watch:output_type -> DeviceReportResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_pkg_proto_device_health_check_proto_init() }
func file_pkg_proto_device_health_check_proto_init() {
	if File_pkg_proto_device_health_check_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pkg_proto_device_health_check_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InitRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_proto_device_health_check_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeviceReportRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_proto_device_health_check_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeviceService); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_proto_device_health_check_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeviceReportResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pkg_proto_device_health_check_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_proto_device_health_check_proto_goTypes,
		DependencyIndexes: file_pkg_proto_device_health_check_proto_depIdxs,
		EnumInfos:         file_pkg_proto_device_health_check_proto_enumTypes,
		MessageInfos:      file_pkg_proto_device_health_check_proto_msgTypes,
	}.Build()
	File_pkg_proto_device_health_check_proto = out.File
	file_pkg_proto_device_health_check_proto_rawDesc = nil
	file_pkg_proto_device_health_check_proto_goTypes = nil
	file_pkg_proto_device_health_check_proto_depIdxs = nil
}
