// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.21.2
// source: pkg/proto/monitor.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OIDRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MachineID string `protobuf:"bytes,1,opt,name=machineID,proto3" json:"machineID,omitempty"`
	Oid       string `protobuf:"bytes,2,opt,name=oid,proto3" json:"oid,omitempty"`
	ValueType string `protobuf:"bytes,3,opt,name=valueType,proto3" json:"valueType,omitempty"`
	Value     string `protobuf:"bytes,4,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *OIDRequest) Reset() {
	*x = OIDRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_monitor_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OIDRequest) ProtoMessage() {}

func (x *OIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_monitor_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OIDRequest.ProtoReflect.Descriptor instead.
func (*OIDRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_monitor_proto_rawDescGZIP(), []int{0}
}

func (x *OIDRequest) GetMachineID() string {
	if x != nil {
		return x.MachineID
	}
	return ""
}

func (x *OIDRequest) GetOid() string {
	if x != nil {
		return x.Oid
	}
	return ""
}

func (x *OIDRequest) GetValueType() string {
	if x != nil {
		return x.ValueType
	}
	return ""
}

func (x *OIDRequest) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type OIDReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SysTime *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=sysTime,proto3" json:"sysTime,omitempty"`
}

func (x *OIDReply) Reset() {
	*x = OIDReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_monitor_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OIDReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OIDReply) ProtoMessage() {}

func (x *OIDReply) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_monitor_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OIDReply.ProtoReflect.Descriptor instead.
func (*OIDReply) Descriptor() ([]byte, []int) {
	return file_pkg_proto_monitor_proto_rawDescGZIP(), []int{1}
}

func (x *OIDReply) GetSysTime() *timestamppb.Timestamp {
	if x != nil {
		return x.SysTime
	}
	return nil
}

var File_pkg_proto_monitor_proto protoreflect.FileDescriptor

var file_pkg_proto_monitor_proto_rawDesc = []byte{
	0x0a, 0x17, 0x70, 0x6b, 0x67, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6d, 0x6f, 0x6e, 0x69,
	0x74, 0x6f, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c,
	0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73,
	0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x70, 0x0a, 0x0a, 0x4f, 0x49,
	0x44, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x6d, 0x61, 0x63, 0x68,
	0x69, 0x6e, 0x65, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x6d, 0x61, 0x63,
	0x68, 0x69, 0x6e, 0x65, 0x49, 0x44, 0x12, 0x10, 0x0a, 0x03, 0x6f, 0x69, 0x64, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x03, 0x6f, 0x69, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x76, 0x61, 0x6c, 0x75,
	0x65, 0x54, 0x79, 0x70, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x76, 0x61, 0x6c,
	0x75, 0x65, 0x54, 0x79, 0x70, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x40, 0x0a, 0x08,
	0x4f, 0x49, 0x44, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x34, 0x0a, 0x07, 0x73, 0x79, 0x73, 0x54,
	0x69, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67,
	0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65,
	0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x07, 0x73, 0x79, 0x73, 0x54, 0x69, 0x6d, 0x65, 0x32, 0x36,
	0x0a, 0x0e, 0x4d, 0x6f, 0x6e, 0x69, 0x74, 0x6f, 0x72, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x12, 0x24, 0x0a, 0x06, 0x52, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x12, 0x0b, 0x2e, 0x4f, 0x49, 0x44,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x09, 0x2e, 0x4f, 0x49, 0x44, 0x52, 0x65, 0x70,
	0x6c, 0x79, 0x22, 0x00, 0x28, 0x01, 0x42, 0x2c, 0x0a, 0x13, 0x63, 0x6e, 0x2e, 0x61, 0x63, 0x2e,
	0x6e, 0x74, 0x73, 0x63, 0x2e, 0x74, 0x61, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x42, 0x0c, 0x4d,
	0x6f, 0x6e, 0x69, 0x74, 0x6f, 0x72, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x50, 0x01, 0x5a, 0x05, 0x2e,
	0x2f, 0x3b, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pkg_proto_monitor_proto_rawDescOnce sync.Once
	file_pkg_proto_monitor_proto_rawDescData = file_pkg_proto_monitor_proto_rawDesc
)

func file_pkg_proto_monitor_proto_rawDescGZIP() []byte {
	file_pkg_proto_monitor_proto_rawDescOnce.Do(func() {
		file_pkg_proto_monitor_proto_rawDescData = protoimpl.X.CompressGZIP(file_pkg_proto_monitor_proto_rawDescData)
	})
	return file_pkg_proto_monitor_proto_rawDescData
}

var file_pkg_proto_monitor_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_pkg_proto_monitor_proto_goTypes = []interface{}{
	(*OIDRequest)(nil),            // 0: OIDRequest
	(*OIDReply)(nil),              // 1: OIDReply
	(*timestamppb.Timestamp)(nil), // 2: google.protobuf.Timestamp
}
var file_pkg_proto_monitor_proto_depIdxs = []int32{
	2, // 0: OIDReply.sysTime:type_name -> google.protobuf.Timestamp
	0, // 1: MonitorService.Report:input_type -> OIDRequest
	1, // 2: MonitorService.Report:output_type -> OIDReply
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_pkg_proto_monitor_proto_init() }
func file_pkg_proto_monitor_proto_init() {
	if File_pkg_proto_monitor_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pkg_proto_monitor_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OIDRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_proto_monitor_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OIDReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pkg_proto_monitor_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_proto_monitor_proto_goTypes,
		DependencyIndexes: file_pkg_proto_monitor_proto_depIdxs,
		MessageInfos:      file_pkg_proto_monitor_proto_msgTypes,
	}.Build()
	File_pkg_proto_monitor_proto = out.File
	file_pkg_proto_monitor_proto_rawDesc = nil
	file_pkg_proto_monitor_proto_goTypes = nil
	file_pkg_proto_monitor_proto_depIdxs = nil
}
